{"report": {"environment": {"Python": "3.10.13", "Platform": "Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36"}, "tests": [{"name": "test_pytest.py::test_example", "duration": 0.0027280270000176188, "run_index": 0, "setup": {"name": "setup", "duration": 0.0008610540000120182, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0004655070000012529, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.0005404119999923296, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_pytest.py::test_another_example", "duration": 0.0018359370000666786, "run_index": 1, "setup": {"name": "setup", "duration": 0.000541804000022239, "outcome": "passed"}, "call": {"name": "call", "duration": 0.000401607000014792, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.0003507220000074085, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_pytest2.py::test_1_plus_1", "duration": 0.003826907999979312, "run_index": 2, "setup": {"name": "setup", "duration": 0.0009334069999908934, "outcome": "passed"}, "call": {"name": "call", "duration": 0.001238248999982261, "outcome": "failed", "longrepr": "def test_1_plus_1():\n>       assert 1 + 1 == 3\nE       assert (1 + 1) == 3\n\ntest_pytest2.py:2: AssertionError"}, "teardown": {"name": "teardown", "duration": 0.0007218450000152643, "outcome": "passed"}, "outcome": "failed"}], "summary": {"passed": 2, "failed": 1, "num_tests": 3, "duration": 0.22345781326293945}, "created_at": "2023-12-13 06:11:17.583039"}}