{"report": {"environment": {"Python": "3.10.13", "Platform": "Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36"}, "tests": [{"name": "test_nodejs.py::test_api_response", "duration": 0.03627628100048241, "run_index": 0, "setup": {"name": "setup", "duration": 0.0012226400003783056, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0330176859997664, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.0008133149999594025, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_pytest.py::test_example", "duration": 0.008945771000071545, "run_index": 1, "setup": {"name": "setup", "duration": 0.0038159400000949972, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0006844300000921066, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.000629460999789444, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_pytest.py::test_another_example", "duration": 0.003032970999356621, "run_index": 2, "setup": {"name": "setup", "duration": 0.0009108719996220316, "outcome": "passed"}, "call": {"name": "call", "duration": 0.000629246999778843, "outcome": "passed"}, "teardown": {"name": "teardown", "duration": 0.000581980000333715, "outcome": "passed"}, "outcome": "passed"}, {"name": "test_pytest2.py::test_1_plus_1", "duration": 0.003235526999560534, "run_index": 3, "setup": {"name": "setup", "duration": 0.0007188749996203114, "outcome": "passed"}, "call": {"name": "call", "duration": 0.001142005000019708, "outcome": "failed", "longrepr": "def test_1_plus_1():\n>       assert 1 + 1 == 3\nE       assert (1 + 1) == 3\n\ntest_pytest2.py:2: AssertionError"}, "teardown": {"name": "teardown", "duration": 0.0006557720003002032, "outcome": "passed"}, "outcome": "failed"}, {"name": "test_pytest2.py::test_mysql_connection", "duration": 0.002797843000280409, "run_index": 4, "setup": {"name": "setup", "duration": 0.0006324850000964943, "outcome": "passed"}, "call": {"name": "call", "duration": 0.0004590700000335346, "outcome": "failed", "longrepr": "def test_mysql_connection():\n        # MySQL database configuration\n        config = {\n            'host': 'localhost',\n            'port': 3306,\n            'user': 'docker',\n            'password': 'docker',\n            'database': 'database_project'\n        }\n    \n        try:\n            # Establish a connection to the MySQL server\n>           connection = mysql.connector.connect(**config)\nE           NameError: name 'mysql' is not defined\n\ntest_pytest2.py:16: NameError\n\nDuring handling of the above exception, another exception occurred:\n\n    def test_mysql_connection():\n        # MySQL database configuration\n        config = {\n            'host': 'localhost',\n            'port': 3306,\n            'user': 'docker',\n            'password': 'docker',\n            'database': 'database_project'\n        }\n    \n        try:\n            # Establish a connection to the MySQL server\n            connection = mysql.connector.connect(**config)\n    \n            assert connection.is_connected()\n    \n>       except mysql.connector.Error as e:\nE       NameError: name 'mysql' is not defined\n\ntest_pytest2.py:20: NameError\n\nDuring handling of the above exception, another exception occurred:\n\n    def test_mysql_connection():\n        # MySQL database configuration\n        config = {\n            'host': 'localhost',\n            'port': 3306,\n            'user': 'docker',\n            'password': 'docker',\n            'database': 'database_project'\n        }\n    \n        try:\n            # Establish a connection to the MySQL server\n            connection = mysql.connector.connect(**config)\n    \n            assert connection.is_connected()\n    \n        except mysql.connector.Error as e:\n            pytest.fail(f\"Error: {e}\")\n    \n        finally:\n            # Close the database connection\n>           if connection.is_connected():\nE           UnboundLocalError: local variable 'connection' referenced before assignment\n\ntest_pytest2.py:25: UnboundLocalError"}, "teardown": {"name": "teardown", "duration": 0.0010738030000538856, "outcome": "passed"}, "outcome": "failed"}], "summary": {"passed": 3, "failed": 2, "num_tests": 5, "duration": 0.683586835861206}, "created_at": "2023-12-20 04:59:54.923854"}}